import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import Navbar from "@/app/components/Navbar";
import "@/app/globals.css";
import Footer from "../components/Footer";
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700']
});

export const metadata: Metadata = {
  title: "SCWS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}`}
      >
        <Navbar />
        <main className="mt-16 min-h-screen max-w-max w-full lg:w-10/12 px-4 p-2 lg:px-8 mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
